# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xiaohan Zhang
email: xiaohanzhang14@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Xiaohan builds a website. Buttery and smooth, always.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://butterytoast.com" # the base hostname & protocol for your site
twitter_username: justxiaohan
github_username:  justxiaohan

# Build settings
markdown: kramdown
